if(NOT CROSS_COMPILER_PATH)
	set(CROSS_COMPILER_PATH "/usr/bin")
endif()
if(NOT CROSS_COMPILER_PREFIX)
	set(CROSS_COMPILER_PREFIX "arm-linux-gnueabihf-")
endif()
#Set Cross compiler
include(cmake/RaspberryPi.cmake)
# Raspberry Pi OS ships CLang 11 in its repositories (in bullseye main and buster backports)
set(CLANG_FOUND /usr/bin/clang-11)
set(LLVM_LINK_FOUND /usr/bin/llvm-link-11)
set(CLANG_VERSION_STRING 11)
if (SYSROOT_CROSS)
  # set(CMAKE_SYSROOT ${SYSROOT_CROSS})
  set(CMAKE_FIND_ROOT_PATH ${SYSROOT_CROSS})
  set(SYSROOT_LIBRARY_FLAGS "-Wl,-rpath-link,${SYSROOT_CROSS}/lib/arm-linux-gnueabihf:${SYSROOT_CROSS}/usr/lib/arm-linux-gnueabihf")
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
